dotfiles:
    # This module automatically compiles all filenames within $XDG_CONFIG_HOME
    # prefixed with 'template.'. It removes the prefix for the compile target,
    # placing it in the same directory as the template.
    on_startup:
        compile:
            content: $XDG_CONFIG_HOME
            target: $XDG_CONFIG_HOME
            include: 'template\.(.+)'


polybar:
    requires:
        - installed: polybar

    on_startup:
        compile:
            - content: modules/polybar/config.template

        run:
            - shell: killall -q polybar
            - shell: polybar --config={modules/polybar/config.template} --reload HDMI2
            - shell: polybar --config={modules/polybar/config.template} --reload eDP1

    on_modified:
        modules/polybar/config.template:
            compile:
                - content: modules/polybar/config.template


terminals:
    # By default, this module is not enabled, since it overwrites possibly
    # pre-existing configuration files. Enable it in config/modules.
    #
    # This module uses the color scheme context syntax from:
    # github::jakobgm/color-schemes.astrality
    # And the color scheme can be changed in context/color_schemes_config
    #
    # It makes it easy to change color schemes for all your terminals at the
    # same time.
    #
    # Terminals:
    # Alacritty: https://github.com/jwilm/alacritty
    # Kitty: https://github.com/kovidgoyal/kitty

    requires:
        - installed: 'alacritty'
        - installed: 'kitty'

    on_startup:
        compile:
            - content: modules/terminals/alacritty.yml.template
              target: {{ env.XDG_CONFIG_HOME }}/alacritty/alacritty.yml
            - content: modules/terminals/kitty.conf.template
              target: {{ env.XDG_CONFIG_HOME }}/kitty/kitty.conf
